package.json

1. Updated `package.json` to point `"homepage"` and `"repository"` sections to the actual repository;
2. Added `"bugs"` section.

chore: update repository and homepage, add bugs

---

owc-app/package.json
package.json
src/generators/linting-eslint-ts/templates/_package.json
src/generators/linting-eslint/templates/_package.json
test/snapshots/fully-loaded-app/package.json
yarn.lock

Depends on https://github.com/open-wc/open-wc/pull/1945

feat: update eslint config

---

package.json
src/core.js
test/core.test.js
yarn.lock

To answer to issue I did report couple of weeks ago #4 
1. Adding dependency to EJS .
2. Calling render method of EJS .
3. Modifying unit test
Previously variables where not mandatory, now with EJS all variable must be filled and provided
4. Update yarn.lock

Feat/template engine#4

---

src/generators/app-lit-element-ts/templates/_MyApp.ts
src/generators/app-lit-element/templates/_MyApp.js
test/snapshots/fully-loaded-app/src/ScaffoldApp.js

Update incorrect links on new projects

---

src/generators/building-rollup-ts/templates/package.json
src/generators/building-rollup/templates/package.json
src/generators/demoing-storybook-ts/templates/package.json
src/generators/demoing-storybook/templates/package.json
src/generators/wc-lit-element-ts/templates/package.json

fix: analyze command

---

src/generators/app/index.js

1 word that would have cleared up issues I was helping a new developer with. Simple and more accurate than present language

Fixes #53 Add word lowercase

---

src/generators/common-repo/templates/static/.vscode/extensions.json

1. Implements https://github.com/open-wc/open-wc/discussions/2245

feat: Adds vscode extension recommendations

---

src/generators/app-lit-element-ts/templates/my-app.test.ts
src/generators/app-lit-element-ts/templates/my-app.ts
src/generators/app-lit-element-ts/templates/tsconfig.json
src/generators/wc-lit-element-ts/templates/tsconfig.json

1. Rolled node resolution back to `node`
2. Updating import/export listings for application testing in TS
fixes #85

Module resolution and app testing

---

src/generators/wc-lit-element-ts/templates/static/demo/index.html
src/generators/wc-lit-element/templates/static/demo/index.html

1. Includes both missing `<meta type="viewport">` tags
fixes #92

fix: ensure all index.html files leverage the "viewport" meta tag

---

src/generators/linting-ts/index.js
src/generators/linting-ts/templates/package.json
src/generators/linting-ts/templates/static/.husky/pre-commit
src/generators/linting/index.js
src/generators/linting/templates/package.json
src/generators/linting/templates/static/.husky/pre-commit
test/snapshots/fully-loaded-app/.husky/pre-commit
test/snapshots/fully-loaded-app/package.json

1. Update versions and script locations to latest

feat: update husky to 9.x

---

package.json
src/generators/building-rollup-ts/templates/package.json
src/generators/building-rollup/templates/package.json
test/snapshots/fully-loaded-app/package.json
yarn.lock

1. Use latest `@babel` dependencies.

deps: update @babel dependencies

---

package.json
src/generators/building-rollup-ts/templates/package.json
src/generators/building-rollup/templates/package.json
test/snapshots/fully-loaded-app/package.json
yarn.lock

1. Bumped all dependencies related to Rollup

deps: use latest Rollup depednencies

---

src/generators/app-lit-element-ts/templates/package.json
src/generators/linting-eslint-ts/templates/package.json
src/generators/linting-types-js/templates/package.json
src/generators/testing-ts/templates/package.json
src/generators/wc-lit-element-ts/templates/package.json

deps: use latest TS

---

package.json
src/generators/common-repo/templates/package.json
test/snapshots/fully-loaded-app/package.json
yarn.lock

deps: use latest CEM analyzer

---

src/generators/linting-ts/templates/package.json
src/generators/linting/templates/package.json
test/snapshots/fully-loaded-app/package.json

Updates lint staged

---

src/generators/app-lit-element-ts/templates/package.json
src/generators/wc-lit-element-ts/templates/package.json

deps: update concurrently

---

src/generators/building-rollup-ts/templates/package.json
src/generators/building-rollup/templates/package.json
test/snapshots/fully-loaded-app/package.json

deps: use latest rimraf

---

package.json
src/generators/building-rollup-ts/templates/package.json
src/generators/building-rollup/templates/package.json
test/snapshots/fully-loaded-app/package.json
yarn.lock

deps: use latest deepmerge

---

src/generators/building-rollup-ts/templates/static/rollup.config.js
src/generators/building-rollup/templates/static/rollup.config.js
test/snapshots/fully-loaded-app/rollup.config.js

1. correctly apply rollup config

fix: remove "require" in ESM contexts

---

README.md
src/generators/app/header.js
test/snapshots/fully-loaded-app.output.txt

1. Update in README, CLI and CLI output listing.

fix: correct more info URL in output
